# Car service configuration

apiVersion: v1
kind: Service
metadata:
  name: rental-cars
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8084
    - name: grpc
      port: 6568
  selector:
    app: rental-cars