# Gateway configuration

apiVersion: v1
kind: Service
metadata:
  name: rental-gateway-lb
spec:
  type: LoadBalancer
  ports:
    - name: rest
      port: 8086
      protocol: TCP
      targetPort: 8086
    - name: grpc
      port: 6565
      targetPort: 6565
  selector:
    app: rental-gateway