# Gateway configuration

apiVersion: v1
kind: Service
metadata:
  name: rental-gateway
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8086
    - name: grpc
      port: 6565
  selector:
    app: rental-gateway
