# Payment service configuration

apiVersion: v1
kind: Service
metadata:
  name: rental-payment
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8081
    - name: grpc
      port: 6567
  selector:
    app: rental-payment