# Rent service configuration

apiVersion: v1
kind: Service
metadata:
  name: rental-rents
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8085
    - name: grpc
      port: 6569
  selector:
    app: rental-rents