# User service configuration

apiVersion: v1
kind: Service
metadata:
  name: rental-users
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8082
    - name: grpc
      port: 6556
  selector:
    app: rental-users